/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { act } from '@react-three/fiber'

export function Model(props) {
  
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/desk_mickey_in_chair_typing.gltf')
  const { actions } = useAnimations(animations, group)
  nodes.Wolf3D_Head001.morphTargetInfluences[1] = .7
  // const [eyes, setEyes] = useState(0)
  
  // setInterval(blink, 10000)
  useEffect(() => {
    actions.typing.play()
   
    // console.log(nodes)
    
  })
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="718cfe4bf2d546d1aba2b17f49e24f91objcleanermaterialmergergle">
            <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials.wire_204204204} scale={0.01} />
          </group>
        </group>
        <group name="Sketchfab_model001" position={[-0.09, 0.71, 0.67]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.03}>
          <group name="Team2_Herry_Keyboardfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode">
              <group name="group1">
                <group name="Keyboard_Body">
                  <mesh name="Keyboard_Body_Keyboard_Body1_0" geometry={nodes.Keyboard_Body_Keyboard_Body1_0.geometry} material={materials.Keyboard_Body1} />
                </group>
                <group name="Keys">
                  <mesh name="Keys_Keyboard_Keys_0" geometry={nodes.Keys_Keyboard_Keys_0.geometry} material={materials.Keyboard_Keys} />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="untitled_3" scale={0.004}>
          <group name="Table" position={[-90, -15.76, 231.69]} scale={0.97}>
            <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Good Day']} position={[-204.95, 101.78, 91.09]} scale={0.91} />
            <mesh name="Cube_2" geometry={nodes.Cube_2.geometry} material={materials.Jackpot} position={[0, 192.87, 0]} scale={0.91} />
            <mesh name="Cube_3" geometry={nodes.Cube_3.geometry} material={materials.Rowan} position={[204.95, 101.78, 91.09]} scale={0.91} />
            <mesh name="Cube_4" geometry={nodes.Cube_4.geometry} material={materials.Yolanda} position={[204.95, 101.78, -91.09]} scale={0.91} />
            <mesh name="Cube_5" geometry={nodes.Cube_5.geometry} material={materials['Exotic Life']} position={[-204.95, 101.78, -91.09]} scale={0.91} />
          </group>
          {/* <mesh name="Ellipse" geometry={nodes.Ellipse.geometry} material={materials.Marion} position={[0, -20, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} /> */}
        </group>
        <group name="Mickey">
          <primitive object={nodes.Hips} />
          <skinnedMesh name="Wolf3D_Body001" geometry={nodes.Wolf3D_Body001.geometry} material={materials.Wolf3D_Body} skeleton={nodes.Wolf3D_Body001.skeleton} />
          <skinnedMesh name="Wolf3D_Hair001" geometry={nodes.Wolf3D_Hair001.geometry} material={materials.Wolf3D_Hair} skeleton={nodes.Wolf3D_Hair001.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Bottom001" geometry={nodes.Wolf3D_Outfit_Bottom001.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={nodes.Wolf3D_Outfit_Bottom001.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Footwear001" geometry={nodes.Wolf3D_Outfit_Footwear001.geometry} material={materials.Wolf3D_Outfit_Footwear} skeleton={nodes.Wolf3D_Outfit_Footwear001.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Top001" geometry={nodes.Wolf3D_Outfit_Top001.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Wolf3D_Outfit_Top001.skeleton} />
          <skinnedMesh name="EyeLeft001" geometry={nodes.EyeLeft001.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeLeft001.skeleton} morphTargetDictionary={nodes.EyeLeft001.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft001.morphTargetInfluences} />
          <skinnedMesh name="EyeRight001" geometry={nodes.EyeRight001.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeRight001.skeleton} morphTargetDictionary={nodes.EyeRight001.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight001.morphTargetInfluences} />
          <skinnedMesh name="Wolf3D_Head001" geometry={nodes.Wolf3D_Head001.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Wolf3D_Head001.skeleton} morphTargetDictionary={nodes.Wolf3D_Head001.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head001.morphTargetInfluences} />
          <skinnedMesh name="Wolf3D_Teeth001" geometry={nodes.Wolf3D_Teeth001.geometry} material={materials.Wolf3D_Teeth} skeleton={nodes.Wolf3D_Teeth001.skeleton} morphTargetDictionary={nodes.Wolf3D_Teeth001.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth001.morphTargetInfluences} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/desk_mickey_in_chair_typing.gltf')
