/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Logo(props) {
  const { nodes, materials } = useGLTF('/Logo.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Cool Touch']} />
      <mesh geometry={nodes.Cube_2.geometry} material={materials.Mara} position={[-100, 0, 0]} />
      <mesh geometry={nodes.Cube_3.geometry} material={materials['Horizon Glow']} position={[100, 0, 0]} />
      <mesh geometry={nodes.Cube_4.geometry} material={materials.Beauty} position={[25, 150, 0]} />
      <mesh geometry={nodes.Cube_5.geometry} material={materials.Shelton} position={[200, 50, 0]} />
    </group>
  )
}

useGLTF.preload('/Logo.glb')
