/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Arnau Rocher Alcayde (https://sketchfab.com/ArnauRocherAlcayde)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/mouse-ef5398bffec6477c9443677d5c57177c
title: Mouse
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Mouse(props) {
  const { nodes, materials } = useGLTF('/mouse.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.polySurface5_MAT_Plastic_0.geometry} material={materials.MAT_Plastic} />
          <mesh geometry={nodes.polySurface2_MAT_Emission_0.geometry} material={materials.MAT_Emission} />
          <mesh geometry={nodes.BOTON_CENTRAL_MAT_Plastic_0.geometry} material={materials.MAT_Plastic} />
          <mesh geometry={nodes.polySurface4_MAT_Details_0.geometry} material={materials.MAT_Details} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/mouse.glb')
